import type { LlmModelProfile } from './base.js';

export const PRESET_LLM_MODEL_PROFILES: LlmModelProfile[] = [
  {
    id: 'gpt',
    family: 'gpt',
    adapterKey: 'openai-chat',
    defaultModel: 'gpt-4o-mini',
    matchPrefixes: ['gpt-', 'o1', 'o3', 'o4', 'openai/gpt-', 'openai/o1', 'openai/o3', 'openai/o4'],
    supportsJsonSchema: true,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1 },
  },
  {
    id: 'claude',
    family: 'claude',
    adapterKey: 'anthropic-messages',
    defaultModel: 'claude-3-5-sonnet-latest',
    matchPrefixes: ['claude-'],
    supportsJsonSchema: true,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 0.95, topK: 40 },
  },
  {
    id: 'gemini',
    family: 'gemini',
    adapterKey: 'gemini-native',
    defaultModel: 'gemini-2.5-flash',
    matchPrefixes: ['gemini-'],
    supportsJsonSchema: true,
    supportsReasoning: false,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 0.95, topK: 40 },
  },
  {
    id: 'gemma',
    family: 'gemma',
    adapterKey: 'gemini-native',
    defaultModel: 'gemma-4-31b-it',
    matchPrefixes: ['gemma-', 'google/gemma-'],
    supportsJsonSchema: true,
    supportsReasoning: true,
    supportsTools: false,
    defaultSampling: { temperature: 0.2, topP: 0.95, topK: 40 },
  },
  {
    id: 'mistral',
    family: 'mistral',
    adapterKey: 'mistral-chat',
    defaultModel: 'mistral-small-latest',
    matchPrefixes: ['mistral-', 'ministral-', 'codestral-'],
    supportsJsonSchema: true,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1 },
  },
  {
    id: 'cohere',
    family: 'cohere',
    adapterKey: 'cohere-chat',
    defaultModel: 'command-a-03-2025',
    matchPrefixes: ['command-r', 'command-a', 'cohere-'],
    supportsJsonSchema: true,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1, topK: 0 },
  },
  {
    id: 'xai',
    family: 'xai',
    adapterKey: 'xai-chat',
    defaultModel: 'grok-4-fast-reasoning',
    matchPrefixes: ['grok-'],
    supportsJsonSchema: true,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1 },
  },
  {
    id: 'deepseek',
    family: 'deepseek',
    adapterKey: 'openai-compatible-chat',
    defaultModel: 'deepseek-chat',
    matchPrefixes: ['deepseek-', 'deepseek'],
    supportsJsonSchema: false,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1 },
    defaultReasoning: { mode: 'off' },
  },
  {
    id: 'qwen',
    family: 'qwen',
    adapterKey: 'openai-compatible-chat',
    defaultModel: 'qwen2.5:7b',
    matchPrefixes: ['qwen', 'qwq-', 'qvq-'],
    supportsJsonSchema: false,
    supportsReasoning: true,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1 },
    defaultReasoning: { mode: 'off' },
  },
  {
    id: 'llama',
    family: 'llama',
    adapterKey: 'openai-compatible-chat',
    defaultModel: 'llama-3.1-8b-instruct',
    matchPrefixes: ['llama', 'meta-llama/', 'meta-llama'],
    supportsJsonSchema: false,
    supportsReasoning: false,
    supportsTools: true,
    defaultSampling: { temperature: 0.2, topP: 1 },
    defaultReasoning: { mode: 'off' },
  },
];
